all: demo1 demo2 demo3 demo4

demo1: demo1.cpp
	g++ -Wall -g -o demo1 demo1.cpp ../_public.cpp

demo2: demo2.cpp
	g++ -Wall -g -o demo2 demo2.cpp ../_public.cpp

demo3: demo3.cpp
	g++ -g -o demo3 demo3.cpp ../_public.cpp

demo4: demo4.cpp
	g++ -g -o demo4 demo4.cpp ../_public.cpp

clean:
	rm -f demo1 demo2 demo3 demo4
