all: demo1 demo2 demo3 demo4 demo5 demo6 demo7 demo8 \
     demo9 demo10 demo11 demo12 demo13 demo14 demo15 \
	 demo16 demo17 demo18 demo19 demo20 demo21

demo1: demo1.cpp
	g++ -Wall -g -o demo1 demo1.cpp ../_public.cpp

demo2: demo2.cpp
	g++ -Wall -g -o demo2 demo2.cpp ../_public.cpp

demo3: demo3.cpp
	g++ -g -o demo3 demo3.cpp ../_public.cpp

demo4: demo4.cpp
	g++ -g -o demo4 demo4.cpp ../_public.cpp

demo5: demo5.cpp
	g++ -g -o demo5 demo5.cpp ../_public.cpp

demo6: demo6.cpp
	g++ -g -o demo6 demo6.cpp ../_public.cpp

demo7: demo7.cpp
	g++ -g -o demo7 demo7.cpp ../_public.cpp

demo8: demo8.cpp
	g++ -g -o demo8 demo8.cpp ../_public.cpp

demo9: demo9.cpp
	g++ -g -o demo9 demo9.cpp ../_public.cpp

demo10: demo10.cpp
	g++ -g -o demo10 demo10.cpp ../_public.cpp

demo11: demo11.cpp
	g++ -g -o demo11 demo11.cpp ../_public.cpp

demo12: demo12.cpp
	g++ -g -o demo12 demo12.cpp ../_public.cpp

demo13: demo13.cpp
	g++ -g -o demo13 demo13.cpp ../_public.cpp

demo14: demo14.cpp
	g++ -g -o demo14 demo14.cpp ../_public.cpp

demo15: demo15.cpp
	g++ -g -o demo15 demo15.cpp ../_public.cpp

demo16: demo16.cpp
	g++ -g -o demo16 demo16.cpp ../_public.cpp

demo17: demo17.cpp
	g++ -g -o demo17 demo17.cpp ../_public.cpp

demo18: demo18.cpp
	g++ -g -o demo18 demo18.cpp ../_public.cpp

demo19: demo19.cpp
	g++ -g -o demo19 demo19.cpp ../_public.cpp

demo20: demo20.cpp
	g++ -g -o demo20 demo20.cpp ../_public.cpp

demo21: demo21.cpp
	g++ -g -o demo21 demo21.cpp ../_public.cpp

clean:
	rm -f demo1 demo2 demo3 demo4 demo5 demo6 demo7 demo8
	rm -f demo9 demo10 demo11 demo12 demo13 demo14 demo15
	rm -f demo16 demo17 demo18 demo19 demo20 demo21
