all: demo01 demo02 demo03 demo04

demo01: demo01.cpp
	g++ -g -o demo01 demo01.cpp -lm -lc

demo02: demo02.cpp
	g++ -g -o demo02 demo02.cpp -lm -lc

demo03:demo03.cpp
	g++ -g -o demo03 demo03.cpp -lm -lc

demo04:demo04.cpp
	g++ -g -o demo04 demo04.cpp -lm -lc

clean:
	rm -f demo01 demo02 demo03 demo04