all: demo01 demo02 demo03 demo04 demo05 demo06 demo07 demo08

demo01: demo01.cpp
	g++ -g -o demo01 demo01.cpp -lm -lc

demo02: demo02.cpp
	g++ -g -o demo02 demo02.cpp -lm -lc

demo03:demo03.cpp
	g++ -g -o demo03 demo03.cpp -lm -lc

demo04:demo04.cpp
	g++ -g -o demo04 demo04.cpp -lm -lc

demo05:demo05.cpp
	g++ -g -o demo05 demo05.cpp ../_public.cpp -lm -lc

demo06:demo06.cpp
	g++ -g -o demo06 demo06.cpp ../_public.cpp -lm -lc

demo07:demo07.cpp
	g++ -g -o demo07 demo07.cpp ../_public.cpp -lm -lc

demo08:demo08.cpp
	g++ -g -o demo08 demo08.cpp ../_public.cpp -lm -lc

clean:
	rm -f demo01 demo02 demo03 demo04 demo05 demo06 demo07 demo08